# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 14:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sina_article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.CharField(max_length=200, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('news_url', models.CharField(max_length=200, null=True)),
                ('source', models.CharField(max_length=50, null=True)),
                ('category', models.CharField(max_length=50, null=True)),
                ('put_time', models.DateTimeField(null=True)),
                ('content', models.TextField(null=True)),
                ('comments_url', models.CharField(max_length=250, null=True)),
                ('comments_number', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sina_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.CharField(max_length=200, null=True)),
                ('m_id', models.CharField(max_length=200, unique=True)),
                ('username', models.CharField(max_length=100, null=True)),
                ('comment', models.TextField(null=True)),
                ('put_time', models.DateTimeField(null=True)),
                ('parent_id', models.CharField(max_length=200, null=True)),
                ('agree_count', models.IntegerField(default=0, null=True)),
                ('against_count', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sohu_article',
            fields=[
                ('news_id', models.CharField(max_length=150, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=300, null=True)),
                ('put_time', models.DateTimeField(null=True)),
                ('comments_number', models.IntegerField(null=True)),
                ('content', models.TextField(null=True)),
                ('news_url', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='sohu_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_id', models.CharField(max_length=200, null=True)),
                ('author', models.CharField(max_length=50, null=True)),
                ('datetime', models.DateTimeField(null=True)),
                ('comment', models.TextField(null=True)),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news_opin.sohu_article', verbose_name=b'sohu related news')),
            ],
        ),
        migrations.CreateModel(
            name='tencent_article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.CharField(max_length=100, null=True)),
                ('parent_name', models.CharField(max_length=200, null=True)),
                ('news_url', models.CharField(max_length=200, null=True)),
                ('title', models.CharField(max_length=200, null=True)),
                ('abstract', models.CharField(max_length=200, null=True)),
                ('source', models.CharField(max_length=50, null=True)),
                ('put_time', models.DateTimeField(null=True, verbose_name='')),
                ('content', models.TextField()),
                ('comments_id', models.CharField(max_length=100, null=True)),
                ('comments_url', models.CharField(max_length=200, null=True)),
                ('comments_number', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['-put_time'],
                'verbose_name': '\u817e\u8baf',
            },
        ),
        migrations.CreateModel(
            name='tencent_comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_id', models.CharField(max_length=200, null=True)),
                ('comments_id', models.CharField(max_length=200, null=True)),
                ('username', models.CharField(max_length=200, null=True)),
                ('comment', models.TextField(null=True)),
                ('put_time', models.DateTimeField(null=True)),
                ('sex', models.CharField(max_length=10, null=True)),
                ('reply_id', models.CharField(max_length=200, null=True)),
                ('agree_count', models.IntegerField(default=0, null=True)),
            ],
        ),
    ]
