# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_opin', '0002_auto_20160519_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sina_article',
            name='content',
            field=models.TextField(default=b' ', null=True),
        ),
        migrations.AlterField(
            model_name='sina_comment',
            name='comment',
            field=models.TextField(default=b' ', null=True),
        ),
        migrations.AlterField(
            model_name='sohu_article',
            name='content',
            field=models.TextField(default=b' ', null=True),
        ),
        migrations.AlterField(
            model_name='sohu_comment',
            name='comment',
            field=models.TextField(default=b' ', null=True),
        ),
        migrations.AlterField(
            model_name='tencent_article',
            name='content',
            field=models.TextField(default=b' '),
        ),
        migrations.AlterField(
            model_name='tencent_comment',
            name='comment',
            field=models.TextField(default=b' ', null=True),
        ),
    ]
