# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-19 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_opin', '0003_auto_20160519_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tencent_article',
            name='content',
            field=models.TextField(default=b' ', null=True),
        ),
    ]
